# Generated by Django 3.2.8 on 2021-12-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QR_type', models.CharField(max_length=200)),
                ('mer_code', models.IntegerField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
